[build]
  command = "yarn run build:web"
  publish = "dist"

[build.environment]
  RUSTUP_HOME = "/opt/buildhome/.rustup"
  CARGO_HOME = "/opt/buildhome/.cargo"
  PATH = "/opt/buildhome/.cargo/bin:$PATH"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
